name: Java CI with Maven

on: [push, pull_request]

jobs:
  test:
    name: Run tests against ${{ matrix.server }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: [payara, wildfly, glassfish, tomee, liberty]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Maven
      run: mvn verify -Dmaven.javadoc.skip=true -P ${{ matrix.server }}

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8
#     - name: Build with Maven
#       run: mvn deploy -Dmaven.test.skip -s settings.xml
