name: Automatically update documentation

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate Javadoc
        run: mvn javadoc:javadoc
      - name: Get the current tag
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: Checkout gh-pages branch
        run: |
          git fetch
          git checkout gh-pages
      - name: Create the documentation directory
        run: mkdir -p docs/${{ steps.tag.outputs.tag }}/javadoc
      - name: Copy Javadoc into new directory
        run: |
          cp -R target/site/apidocs/* docs/${{ steps.tag.outputs.tag }}/javadoc
      - name: Commit and push the new docs
        run: |
          git config --local user.email "automation@omnifaces.org"
          git config --local user.name "OmniFaces Bot"
          git add docs
          git commit -m "Update documentation for ${{ steps.tag.outputs.tag }}"
          git push origin gh-pages

